### ISSUE TITLE
Suppressed Brand/Forced Zero Search Results Landing Page

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/LANDING-PAGES#3]
Web Doc: https://docs.google.com/spreadsheets/d/1s31Y4Z5x_o7UfXM-1d54U4MPoyXranR9IelMtWHHDBI/edit#gid=870421774

LP Slug: https://www.c21stores.com/pages/zero-search

**Comment by c21hornak** [comment]
Linking Doc: https://docs.google.com/spreadsheets/d/1s31Y4Z5x_o7UfXM-1d54U4MPoyXranR9IelMtWHHDBI/edit#gid=870421774

**Comment by AdenaG** [comment]
Piggybacking on Michael's email - copy doesn't make sense when there are no designer filters on the page. Direction is not clear, but thats COPY. Also, since the page name is visible to customers, I would call it something better than 'zero search'

Juan - for mobile, are the CTA's supposed to be spaced like that with a larger gap above kids? I didnt see a design for the mobile CTAs on the drive, but the layout it looks a little odd to me. 
![screen shot 2016-07-13 at 1 34 44 pm](https://cloud.githubusercontent.com/assets/20344050/16813241/ae5fef14-48fe-11e6-9d72-8e466ad3f76d.png)

**Comment by juanmriosv** [comment]
These are all things that should be have been called before even building it.

There are constrains on the CTAs (since they are uneven and did not follow character count provided).

**Comment by AdenaG** [comment]
So then they should have been called out by creative and at this point forget it? What abt the page name?

**Comment by juanmriosv** [comment]
Page went back to "in progress" tab. 
Only
